---
title: "Blouch SBR1 -Basic Testing"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
Testing Blouch code just to see if it runs before validation, etc.

##Regimes Models

Using Simulated Regime data from: SBR1 - Cervidae Regime Data Simulations
Known regime values - 4 and 5 with slope of 0.8

Setup stan data file using simulated data - 2 regimes - direct slope covariate
```{r}
library(loo)

source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/R Setup Code/R1/blouchOUReg.setup.mv_v1_3.R")

name.response.trait<-paste("Sim",1,sep="")
print(name.response.trait)
        
#One direct covariate w/o ME
stan_test_data<-blouchOUReg.setup.mv(cervid.2reg.trdata,names.fixed.fact,name.response.trait,names.direct.traits,names.random.traits=NULL)
```


Testing Code
```{r}
setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/") #Macbook Pro
stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/blouchOUReg_MLI.stan") #Macbook Pro

#setwd("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/")#Mac Studio
#stanc("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/blouchOUReg_MLI.stan") #Mac Studio

stan_model <- stan_model("blouchOUReg_MLI.stan")

fit.mli.regimes<- rstan::sampling(object = stan_model,data = stan_test_data,chains = 2,iter = 2000,control=list(adapt_delta=0.80))

print(fit.mli.regimes,pars = c("hl","beta_bar","sigma","beta","beta_e","vy","log_lik"))

#For downstream analysis and plots
```

Plotting
```{r}
stan_dens(fit.mli.regimes,pars = c("hl","beta_bar","sigma","beta","beta_e","vy"))

#For downstream analysis and plots
ext.fit.adaptive.test <- rstan::extract(fit.mli.regimes)

library(ggplot2)
hl<-ext.fit.adaptive.test$hl
vy<-ext.fit.adaptive.test$vy
beta<-ext.fit.adaptive.test$beta

new.data<-data.frame(hl,vy,beta)
ggplot(new.data,aes(x=hl,y=vy))+
  geom_point()

ggplot(new.data,aes(x=hl,y=beta))+
  geom_point()


pairs(fit.mli.regimes,pars=c("hl","beta","vy"))

```

Basic no varying intercepts model
```{r}
setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Current Working Versions/") #Macbook Pro
stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Current Working Versions/blouchOUReg_v1_5.stan") #Macbook Pro

stan_model <- stan_model("blouchOUReg_v1_5.stan")

fit.npi.regimes<- rstan::sampling(object = stan_model,data = stan_test_data,chains = 2,iter = 2000,control=list(adapt_delta=0.80))

print(fit.npi.regimes,pars = c("hl","beta","beta_e","vy","log_lik"))

#For downstream analysis and plots
```

Model Comparisons
```{r}
log_lik_M.mli<-extract_log_lik(fit.mli.regimes, merge_chains = FALSE)
log_lik_M.npi<-extract_log_lik(fit.npi.regimes, merge_chains = FALSE)

r_eff <- relative_eff(exp(log_lik_M.mli), cores = 2) 
loo_1 <- loo(log_lik_M.mli, r_eff = r_eff, cores = 2)

r_eff <- relative_eff(exp(log_lik_M.npi), cores = 2) 
loo_2 <- loo(log_lik_M.npi, r_eff = r_eff, cores = 2)

loo_compare(waic(log_lik_M.mli),waic(log_lik_M.npi))
```




