---
title: "Blouch ms Cervid Analysis SBR1 - Posterior Predictive Checks and SBC"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list=ls())
library(rstan)
library(treeplyr)
library(slouch)
#install.packages("ggpubr")

library(ggpubr)

# Load necessary packages
library(ape)
library(ggplot2)
library(bridgesampling)

#For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)


dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars")
if (!file.exists(M)) file.create(M)
arch <- ifelse(R.version$arch == "aarch64", "arm64", "x86_64")
cat(paste("\nCXX14FLAGS += -O3 -mtune=native -arch", arch, "-ftemplate-depth-256"),
    file = M, sep = "\n", append = FALSE)

```

Data Prep
```{r}
cervid.tree<-read.nexus("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/cervidae_renamed.tre")
#cervid.tree<-read.nexus("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/cervidae_renamed.tre")
cervid.dataset<-read.csv("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/deer_mean_dat.csv")
#cervid.dataset<-read.csv("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/deer_mean_dat.csv")

#Remove Muntiacus_atherodes, Elaphodus_cephalophus - rudamentary and female Rangifer. 
cervid.dataset<-filter(cervid.dataset,Genus_Species != "Sinomegaloceros_yabei" & ! Genus_Species =="Alces_alces_gigas"  & ! Genus_Species == "Muntiacus_truongsonensis" & ! Genus_Species ==  "Mazama_temama"& ! Genus_Species ==  "Muntiacus_feae" & ! Genus_Species ==  "Muntiacus_atherodes" & ! Genus_Species ==  "Elaphodus_cephalophus")


cervid.trdata <- make.treedata(cervid.tree, cervid.dataset,name_column="Genus_Species")
cervid.trdata<-mutate(cervid.trdata,me.log_ant_vol=cervid.trdata$dat$log_vol_var_est/cervid.trdata$dat$n)
cervid.trdata<-mutate(cervid.trdata,me.log_psl=cervid.trdata$dat$log_psl_var_est/cervid.trdata$dat$n)
cervid.trdata<-mutate(cervid.trdata,me.log_male_mass=cervid.trdata$dat$male_logmass_sd^2/cervid.trdata$dat$male_mass_n)
cervid.trdata<-mutate(cervid.trdata,me.log_female_mass=cervid.trdata$dat$female_logmass_sd^2/cervid.trdata$dat$female_mass_n)

cervid.trdata<-filter(cervid.trdata,!(is.na(log_ant_vol)) & !(is.na(log_psl)))
cervid.trdata<-filter(cervid.trdata,!(is.na(male_mass)) & !(is.na(female_mass)))

cervid.trdata<-filter(cervid.trdata,!(is.na(me.log_ant_vol)) & !(is.na(me.log_psl)))

#cervid.trdata<-filter(cervid.trdata, (Status == "Extant")) #Only non-fossil species

cervid.trdata<-mutate(cervid.trdata,male_logmass=log(male_mass))
cervid.trdata<-mutate(cervid.trdata,female_logmass=log(female_mass))

cervid.trdata<-filter(cervid.trdata,!(is.na(me.log_male_mass)) & !(is.na(me.log_female_mass)))


#Mean Standardized
cervid.trdata$dat$mc.log_psl<-cervid.trdata$dat$log_psl-mean(cervid.trdata$dat$log_psl)
cervid.trdata$dat$mc.log_ant_vol<-cervid.trdata$dat$log_ant_vol-mean(cervid.trdata$dat$log_ant_vol)

cervid.trdata$dat$mc.male_logmass<-cervid.trdata$dat$male_logmass-mean(cervid.trdata$dat$male_logmass)
cervid.trdata$dat$mc.female_logmass<-cervid.trdata$dat$female_logmass-mean(cervid.trdata$dat$female_logmass)


```

Rescale Tree to Height =1
```{r}
l.tree<-max(branching.times(cervid.trdata$phy))
cervid.trdata$phy$edge.length<-cervid.trdata$phy$edge.length/l.tree ## rescale tree to height 1
max(branching.times(cervid.trdata$phy))

```

Adaptive Model of Evolution
```{r}
source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/R Setup Code/R1/blouchOU.setup.mv_v1_3.R")
#source("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/R Setup Code/R1/blouchOU.setup.mv_v1_3.R")
#blouchOU.setup.mv<-function(trdata,name.response.trait,names.direct.traits=NULL,names.adaptive.traits=NULL,names.response.me.traits=NULL,names.direct.me.traits=NULL,names.adaptive.me.traits=NULL){
#names.traits<-c("log_ant_vol","log_psl","me.log_ant_vol","me.log_psl")


name.response.trait<-c("mc.log_ant_vol")
names.adaptive.traits<-c("mc.log_psl")
#names.direct.traits<-c("log_psl")
name.response.me.trait<-c("me.log_ant_vol")
#names.direct.me.traits<-c("me.log_psl")
names.adaptive.me.traits<-c("me.log_psl")
#Data must be logged before entry into blouchOU.setup

stan_data<-blouchOU.setup.mv(cervid.trdata,name.response.trait,names.direct.traits=NULL,names.adaptive.traits,name.response.me.trait,names.direct.me.traits=NULL,names.adaptive.me.traits)


stan_data<-stan_data[[1]]
stan_OU1_data<-stan_data[[2]]
```

Plotting half-cauchy
```{r}
par.halfcauchy <- list(location=0, scale=0.01) #Former runs 08/10/2021

samp <- rcauchy(10000, location=par.halfcauchy$location, scale=par.halfcauchy$scale)
samp<-samp[samp>=0]

min(samp)
max(samp)

library(ggsci)
vy.prior.plot<-ggplot(data.frame(Vy = samp),aes(x=Vy))+
  geom_histogram(binwidth=0.01)+
  geom_vline(xintercept=var(stan_data$Y),colour="#BB0000",linetype="dashed")+
  theme_bw()+
  ggtitle("Prior for Vy")+
  ylab("Frequency") + xlab("Vy")+xlim(c(0,10))+
  scale_color_npg()
 
vy.prior.plot

pdf("vy.prior.plot.pdf", width=5, height=5)
vy.prior.plot
dev.off()

```


Prior Predictive Checking
```{r}
#setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
setwd("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
#stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_prior.stan")
stanc("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_prior.stan")

stan_model <- stan_model("blouchOU_v1_8_prior.stan")

prior.fit<- rstan::sampling(object = stan_model,data = stan_data,chains = 1,iter = 4000,control=list(adapt_delta=0.95))

print(prior.fit,pars = c("a","hl","beta","vy","r_squared","sigma2_y"))

```

Plot results
```{r}
y<-stan_data$Y
y_rep <- rstan::extract(prior.fit, pars = "Y_sim")[[1]]
#y$type<-"observed"
y_rep_1<-y_rep[1000,,]
#y_rep_1$type<-"simulated"

y_total<-data.frame(rbind(y,y_rep_1))
prior.plots<-list()       
for(i in 1:6){
  data.set<-NULL
  data.set<-data.frame(y)
  names(data.set)<-c("Observed")
  sim.data<-data.frame(t(y_total[sample(1:NROW(y_total),1),]))
  names(sim.data)<-c("Simulated")
  data.set<-cbind(data.set,sim.data)
  
  prior.plots[[i]]<-ggplot(data.set, aes(x=Observed,y=Simulated))+geom_point()+geom_abline(slope=1,intercept=0)+theme_bw()
}       

all.prior.plots<-ggarrange(prior.plots[[1]]+rremove("xlab"), prior.plots[[2]]+rremove("xlab")+rremove("ylab"),prior.plots[[3]]+rremove("xlab")+rremove("ylab"),prior.plots[[4]],prior.plots[[5]]+rremove("ylab"),prior.plots[[6]]+rremove("ylab"),
          #labels = c("A", "B", "C"),
          ncol = 3, nrow = 2)

all.prior.plots

pdf("prior_plots.pdf",
width=8,
height=5)

#ggarrange(prior.plots[[1]]+rremove("xlab"), prior.plots[[2]]+rremove("xlab")+rremove("ylab"),prior.plots[[3]]+rremove("xlab")+rremove("ylab"),prior.plots[[4]],prior.plots[[5]]+rremove("ylab"),prior.plots[[6]]+rremove("ylab"),
          #labels = c("A", "B", "C"),ncol = 3, nrow = 2)
all.prior.plots
dev.off()



```


Posterior Predictive Checking
```{r}
#setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
setwd("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
#stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_post.stan")
stanc("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_post.stan")

stan_model <- stan_model("blouchOU_v1_8_post.stan")

post.fit<- rstan::sampling(object = stan_model,data = stan_data,chains = 1,iter = 4000,control=list(adapt_delta=0.95))

```

Plot Results
```{r}
library("bayesplot")

color_scheme_set("brightblue")

y_rep <- rstan::extract(post.fit, pars = "Y_pred")[[1]]
y<-stan_data$Y

y_rep_1<-y_rep[sample(1:2000,1),,]

ppc.plot<-ppc_dens_overlay(y, y_rep_1)+xlim(-9,6)
ppc.plot

pdf("post_plots.pdf",
width=8,
height=6)
ppc.plot
dev.off()

min(y)
max(y)
min(y_rep_1)
max(y_rep_1)

```


Simulation Based Calibration - 200 simulations of stan model
```{r}
#setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
#stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_SBC.stan")

setwd("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1")
stanc("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Code/Stan Code/R1/blouchOU_v1_8_post.stan")


stan_model <- stan_model("blouchOU_v1_8_SBC.stan")

ranks<-NULL
for (i in 1:200){
  print(i)
  SBC.fit<- rstan::sampling(object = stan_model,data = stan_data,chains = 1,iter = 4000,control=list(adapt_delta=0.95))
  ranks.SBC.fit <- data.frame(rstan::extract(SBC.fit,pars="ranks_"))
  ranks.SBC.fit<-ranks.SBC.fit[seq(1,dim(ranks.SBC.fit)[1],2),]
  #ranks.SBC.fit<-apply(data.frame(ranks.SBC.fit),2,sample,size=500,replace=FALSE)
  ranks<-rbind(ranks,colSums(ranks.SBC.fit))
}

save.image("~/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Workspaces/SBR1 Model Checking 121222.RData")

```

Plot Results
```{r}

#  array[6] int <lower=0,upper=1> ranks_ = {hl<hl_sim,vy<vy_sim,Ya<Ya_sim,b0<b0_sim,beta[1]<beta1_sim,beta[2]<beta2_sim};

#load("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Workspaces/SBR1_SBC_120922.RData")

#For SBR1
load("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Workspaces/SBR1_SBC_121122.RData")

ranks<-data.frame(ranks)
names(ranks)<-c("hl","vy","Ya","b0","k","b1")

hl.plot<-ggplot(ranks,aes(x=hl))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()
vy.plot<-ggplot(ranks,aes(x=vy))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()
Ya.plot<-ggplot(ranks,aes(x=Ya))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()
b0.plot<-ggplot(ranks,aes(x=b0))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()
k.plot<-ggplot(ranks,aes(x=k))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()
b1.plot<-ggplot(ranks,aes(x=b1))+geom_histogram(binwidth=50,color="black",fill="white")+theme_bw()

plot_list<-list(hl.plot,vy.plot,Ya.plot,b0.plot,k.plot,b1.plot)

sbc.plots<-ggarrange(plotlist = plot_list,
          ncol = 3, nrow = 2)

       
sbc.plots

pdf("SBC_plots_121322.pdf",
width=8,
height=5)

ggarrange(plotlist = plot_list,
          ncol = 3, nrow = 2)

dev.off()

ks.test(ranks[,1],"punif",0,1000)
ks.test(ranks[,2],"punif",0,1000)
ks.test(ranks[3],"punif",0,1000)
ks.test(ranks[,4],"punif",0,1000)
ks.test(ranks[,5],"punif",0,1000)
ks.test(ranks[,6],"punif",0,1000)


plot(ecdf(ranks[,1]))
curve(punif(x, 0, 1000), add=TRUE, col="red")

plot_list<-list(hl.plot,vy.plot,Ya.plot,b0.plot,k.plot,b1.plot)



```

