---
title: "SBR1 - Blouch Testing - BM Sim Plots"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Load functions used for testing
```{r}
#library(mvMORPH)
rm(list=ls())
library(rstan)
library(treeplyr)
library(slouch)
#For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores())

library(mvSLOUCH)
#library(bayou)
library(PCMBaseCpp)
library(treeplyr)
library(TreeSim)
library(ggsci)
library(ggplot2)
library(plotly)

dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars")
if (!file.exists(M)) file.create(M)
arch <- ifelse(R.version$arch == "aarch64", "arm64", "x86_64")
cat(paste("\nCXX14FLAGS += -O3 -mtune=native -arch", arch, "-ftemplate-depth-256"),
    file = M, sep = "\n", append = FALSE)
```

Data Prep
```{r}
#cervid.tree<-read.nexus("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/cervidae_renamed.tre")

cervid.tree<-read.nexus("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/cervidae_renamed.tre")


#cervid.dataset<-read.csv("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/deer_mean_dat.csv")

cervid.dataset<-read.csv("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/Original Submission/Data/Antler Dataset/deer_mean_dat.csv")

#Remove Muntiacus_atherodes, Elaphodus_cephalophus - rudamentary and female Rangifer. 
cervid.dataset<-filter(cervid.dataset,Genus_Species != "Sinomegaloceros_yabei" & ! Genus_Species =="Alces_alces_gigas"  & ! Genus_Species == "Muntiacus_truongsonensis" & ! Genus_Species ==  "Mazama_temama"& ! Genus_Species ==  "Muntiacus_feae" & ! Genus_Species ==  "Muntiacus_atherodes" & ! Genus_Species ==  "Elaphodus_cephalophus")


cervid.trdata <- make.treedata(cervid.tree, cervid.dataset,name_column="Genus_Species")
cervid.trdata<-mutate(cervid.trdata,me.log_ant_vol=cervid.trdata$dat$log_vol_var_est/cervid.trdata$dat$n)
cervid.trdata<-mutate(cervid.trdata,me.log_psl=cervid.trdata$dat$log_psl_var_est/cervid.trdata$dat$n)

cervid.trdata<-mutate(cervid.trdata,mc.log_ant_vol=log_ant_vol-(mean(log_ant_vol)),mc.log_psl=log_psl-mean(log_psl))


names.traits<-c("mc.log_ant_vol","mc.log_psl",NA,NA)

#names.traits<-c("mc.log_ant_vol","mc.log_psl","me.log_ant_vol","me.log_psl")
cervid.trdata<-filter(cervid.trdata,!(is.na(log_ant_vol)) & !(is.na(log_psl)))
cervid.trdata<-filter(cervid.trdata,!(is.na(me.log_ant_vol)) & !(is.na(me.log_psl)))
cervid.trdata


```

Rescale Tree to Height =1
```{r}
l.tree<-max(branching.times(cervid.trdata$phy))
cervid.trdata$phy$edge.length<-cervid.trdata$phy$edge.length/l.tree ## rescale tree to height 1
max(branching.times(cervid.trdata$phy))

```






Number of iterations per half life
```{r}
N<-10
```



#######################

Brownian motion Loops

Brownian Slope Accuracy Simulation Loops
```{r}
source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1/Blouch Testing - SBR1/Functions/SBR1.stan.OU.adapt.inac.hl.R")
#source("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro (1)/Academic/Research/Current Projects/Blouch project/R1/Blouch Testing - SBR1/Functions/SBR1.stan.OU.adapt.inac.hl.R")
saved.bpa<-NULL
saved.parameters<-NULL

##################################
brown.slope<-0.25
#sigma2y.list<-seq(from=0.05, to=1, by=0.05)
sigma2y.list<-c(0.01,0.05,0.1,0.25,0.5,0.75,1.0,2.0)

#tips.list<-c(32,64,126)

#Mean centered X
vX0 <- 0

##################################
sim<-stan.BM.inac.hl(tips.list=NULL,cervid.trdata$phy,N,brown.slope,vX0,sigma2y.list)
saved.parameters<-rbind(saved.parameters,sim[[1]])
saved.bpa<-rbind(saved.bpa,sim[[2]])

```

```{r}
save.image(file = "SBR1 - Blouch Testing - BM Sim Plots - WS_101422.RData")

```


Plot of Posterior Medians
```{r}
#saved.parameters.sub<-saved.parameters%>%filter(vy==0.01)
brown.plot<-ggplot(saved.parameters,aes(y=brown.slope.median,x=factor(sigma2y),group=1))+
  geom_point(aes(y=0.25),size=2.0,alpha=0.8,color="black")+
  geom_point(size=1.0,alpha=0.4)+
  geom_point(stat='summary', fun=mean)+
  stat_summary(fun=mean, geom="line")+

  #geom_line(data=mean.opt.slopes, aes(y=mean.opt,x=factor(hl)),lty=2)+
  theme_bw()+
  #theme(legend.position="bottom")+
  ggtitle("Optimal Slope")+
  #ggtitle("Evolutionary Regression Slope")+
  #ggtitle("Phylogenetic Half-life")+
  ylab("Posterior Mean") + xlab("Sigma2y")+
  #ylim(c(0,0.5))+
  scale_color_npg()+
  scale_x_discrete(breaks=seq(0, 1, 0.1))


brown.plot
 
#saved.parameters.sub<-saved.parameters%>%filter(vy==0.01)
sigma.plot<-ggplot(saved.parameters,aes(y=sigma2y.median,x=factor(sigma2y),group=1))+
  geom_point(aes(y=sigma2y),size=2.0,alpha=0.8,color="black")+
  geom_point(size=1.0,alpha=0.4)+
  geom_point(stat='summary', fun=mean)+
  stat_summary(fun=mean, geom="line")+

  #geom_line(data=mean.opt.slopes, aes(y=mean.opt,x=factor(hl)),lty=2)+
  theme_bw()+
  #theme(legend.position="bottom")+
  ggtitle("Optimal Slope")+
  #ggtitle("Evolutionary Regression Slope")+
  #ggtitle("Phylogenetic Half-life")+
  ylab("Posterior Mean") + xlab("Sigma2y")+
  #ylim(c(0,0.5))+
  scale_color_npg()+
    scale_x_discrete(breaks=seq(0, 1, 0.1))


sigma.plot
 


```



```{r}
library(ggpubr)
pdf("plots_blouch_BM.pdf", width=6, height=3)
ggarrange(brown.plot,sigma.plot,ncol=2,nrow=1)

dev.off()

```

