---
title: "SBR1 Cervidae Regime Simulation Analysis"
output: html_notebook
---

Using simulated data fromm SBR1 Cervidae Regime Simulation Code

Testing Multi-Level Regimes/Intercepts Model
```{r}

#setwd("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Simulation Code/Stan Models/") #Macbook Pro
#stanc("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Simulation Code/Stan Models/simRegimes_XY.stan") #Macbook Pro

setwd("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/")#Mac Studio
stanc("/Users/markgrabowski/Library/CloudStorage/GoogleDrive-mark.walter.grabowski@gmail.com/Other computers/My MacBook Pro/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Stan Models Milestones/Testing Versions/blouchOUReg_MLI.stan") #Mac Studio

stan_model <- stan_model("blouchOUReg_MLI.stan")

fit.simdata<- rstan::sampling(object = stan_model,data = stan_sim_data,chains = 2,iter = 2000,control=list(adapt_delta=0.95),algorithm=c("Fixed_param"))

#For downstream analysis and plots
ext.fit.simdata <- rstan::extract(fit.simdata)


```




Inaccuracy loops for simulated repeated optima
```{r}
source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Validation Code/SBR1 Inaccuracy Loops/repeated_optima_sim.R")

names.traits<-c("mc.log_psl","NA","regimes")
#name.response.trait<-c("log_ant_vol")
#names.adaptive.traits<-c("mc.log_psl")
#names.direct.traits<-c("mc.log_psl")
#name.response.me.trait<-c("me.log_ant_vol")
#names.adaptive.me.traits<-c("me.log_psl")
#names.direct.me.traits<-c("me.log_psl")
#names.fixed.fact<-c("regimes")

error.comparison.2reg<-repeated_optima_sim(cervid.3reg.trdata,n=10,names.traits,head(optima,-1))
error.comparison.2reg
```

```{r}
source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Validation Code/SBR1 Inaccuracy Loops/repeated_optima_sim.R")

names.traits<-c("mc.log_psl","NA","regimes")
#name.response.trait<-c("log_ant_vol")
#names.adaptive.traits<-c("mc.log_psl")
#names.direct.traits<-c("mc.log_psl")
#name.response.me.trait<-c("me.log_ant_vol")
#names.adaptive.me.traits<-c("me.log_psl")
#names.direct.me.traits<-c("me.log_psl")
#names.fixed.fact<-c("regimes")

error.comparison.3reg<-repeated_optima_sim(cervid.3reg.trdata,n=10,names.traits,head(optima,-1))
error.comparison.3reg
```


```{r}
source("/Users/markgrabowski/Documents/Academic/Research/Current Projects/Blouch project/R1 blouch-testing branch/Validation Code/SBR1 Inaccuracy Loops/repeated_optima_sim.R")

names.traits<-c("mc.log_psl","NA","regimes")
#name.response.trait<-c("log_ant_vol")
#names.adaptive.traits<-c("mc.log_psl")
#names.direct.traits<-c("mc.log_psl")
#name.response.me.trait<-c("me.log_ant_vol")
#names.adaptive.me.traits<-c("me.log_psl")
#names.direct.me.traits<-c("me.log_psl")
#names.fixed.fact<-c("regimes")

error.comparison.4reg<-repeated_optima_sim(cervid.4reg.trdata,n=10,names.traits,head(optima,-1))
error.comparison.4reg
```



Plot Regimes
```{r}
errors.combined<-data.frame(t(cbind(error.comparison.2reg[[3]],error.comparison.3reg[[3]],error.comparison.4reg[[3]])))
errors.combined<-cbind(errors.combined,reps=1:30,regimes=c(rep(2,10),rep(3,10),rep(4,10)))
regimes<-c(2,3,4)
mean.errors.combined<-data.frame(errors.combined%>%group_by(regimes)%>%mutate(mlm.mean=mean(mlm.inaccuracy),npm.mean=mean(npm.inaccuracy)))

mean.errors.combined%>%group_by(regimes)%>%
#errors.combined%>%
  ggplot(aes(x=reps,group=regimes))+
  geom_point(aes(y=mlm.inaccuracy),size=2.0,alpha=0.8)+
  geom_point(aes(y=npm.inaccuracy),shape=21,size=2.0,alpha=0.8)+
  geom_line(aes(x=reps,y=mlm.mean),linetype="solid")+
  geom_line(aes(x=reps,y=npm.mean),linetype="dashed")+
  geom_vline(xintercept=c(10.5,20.5),alpha=0.75,linetype="dotted")+
  ylab("Imprecision") + xlab("Regimes")+
  theme_bw()+
  scale_color_npg()+
  #theme(legend.text)
  scale_x_continuous(breaks=c(5,15,25),labels=regimes)
  #geom_label(label=c(""))


  


```